=== Yura09/task11_XML/src/main/resources/gem/gemsXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name='gems'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name='gem' type='gemType' minOccurs='0'
                            maxOccurs='unbounded'/>
            </xs:sequence>
            <xs:attribute name='noNamespaceSchemaLocation' type='xs:string'/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="gemType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"></xs:element>
            <xs:element name="preciousness">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="PRECIOUS|SEMIPRECIOUS"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="origin" type="xs:string"></xs:element>
            <xs:element name="visual">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="color" type="xs:string"></xs:element>
                        <xs:element name="transparency">
                            <xs:simpleType>
                                <xs:restriction base="xs:double">
                                    <xs:minInclusive value="0"/>
                                    <xs:maxInclusive value="100"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="engraving">
                            <xs:simpleType>
                                <xs:restriction base="xs:int">
                                    <xs:minInclusive value="4"/>
                                    <xs:maxInclusive value="15"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="value">
                <xs:simpleType>
                    <xs:restriction base="xs:double">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"></xs:attribute>
    </xs:complexType>

</xs:schema>

=== Yura09/task11_XML/src/main/resources/gem/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="gemsXSL.xsl"?>

<gems
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="gemsXSD.xsd">

<gem id="1">
        <name>diamond</name>
        <preciousness>PRECIOUS</preciousness>
        <origin>USA</origin>
        <visual>
            <color>white</color>
            <transparency>70</transparency>
            <engraving>8</engraving>
        </visual>
        <value>2</value>

    </gem>
    <gem id="2">
        <name>ruby</name>
        <preciousness>SEMIPRECIOUS</preciousness>
        <origin>Poland</origin>
        <visual>
            <color>red</color>
            <transparency>40.5</transparency>
            <engraving>5</engraving>
        </visual>
        <value>3</value>

    </gem>
    <gem id="3">
        <name>sapphire</name>
        <preciousness>PRECIOUS</preciousness>
        <origin>China</origin>
        <visual>
            <color>blue</color>
            <transparency>69</transparency>
            <engraving>13</engraving>
        </visual>
        <value>3</value>

    </gem>
</gems>
